version: "3.9"

services:
  python-testbed:
    image: python:3.6-slim
    tty: true
    ipc: "host"
    working_dir: /app
    volumes:
      - ./:/app

  elasticsearch:
    image: elasticsearch:7.12.0
    restart: unless-stopped
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./esdata:/usr/share/elasticsearch/data

  kibana:
    image: kibana:7.12.0
    restart: unless-stopped
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
